version: "3.7"
services:
  frontend:
    build:
      context: ./oslo-vue-frontend
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    ports:
    - 8081:8080
  backend:
    build:
      context: ./oslo-itb-rdf-validator
      dockerfile: Dockerfile
    ports:
    - 8080:8080
